version: "3"
services:
  app:
    image: laravel-www
    container_name: laravel-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mysql
      - redis
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  mysql:
    container_name: laravel-mysql
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 13306:3306
  redis:
    container_name: laravel-redis
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data
  composer:
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    volumes:
      - .:/var/www/html
#  git:
#    container_name: git
#    image: bitnami/git:latest
#    volumes:
#      - .:/var/www/html
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
  composer:
    driver: "local"
