version: "3"
services:
  app:
    image: laravel-www
    container_name: laravel-www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel.local
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mysql
      - redis
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: app
    ports:
      - 8080:80
  scheduler:
    image: laravel-www
    container_name: laravel-scheduler
    networks:
      - laravel.local
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: scheduler
    depends_on:
      - app
      - mysql
      - redis
  queue:
    image: laravel-www
    container_name: laravel-queue
    networks:
      - laravel.local
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: queue
    depends_on:
      - app
      - mysql
      - redis
  mysql:
    container_name: laravel-mysql
    image: mysql:5.7
    networks:
      - laravel.local
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 13306:3306
  redis:
    container_name: laravel-redis
    image: redis:4-alpine
    networks:
      - laravel.local
    ports:
      - 16379:6379
    volumes:
      - redis:/data
  composer:
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    networks:
      - laravel.local
    volumes:
      - .:/var/www/html
#  git:
#    container_name: git
#    image: bitnami/git:latest
#    volumes:
#      - .:/var/www/html
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
  composer:
    driver: "local"

#  On ubuntu try networks
#  @link:https://superuser.com/questions/1668461/xubuntu-20-4-xdebug-3-and-docker-impossible-to-connect-from-container-to-host </br>
networks:
  laravel.local:
